import argparse
import configparser
import csv
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate HEROHE MIRAX slide folders against Slidedat.ini file list."
    )
    parser.add_argument(
        "--manifest_csv",
        type=Path,
        required=True,
        help="Manifest CSV generated by build_herohe_manifest.py",
    )
    parser.add_argument(
        "--output_csv",
        type=Path,
        required=True,
        help="Output integrity report CSV path.",
    )
    return parser.parse_args()


def expected_datafiles(slide_ini_path: Path):
    cfg = configparser.ConfigParser(strict=False)
    cfg.optionxform = str
    with slide_ini_path.open("r", encoding="utf-8-sig", errors="ignore") as f:
        cfg.read_file(f)

    if "DATAFILE" not in cfg:
        return []
    section = cfg["DATAFILE"]
    count = int(section.get("FILE_COUNT", 0))
    files = []
    for i in range(count):
        key = f"FILE_{i}"
        if key in section:
            files.append(section[key].strip())
    return files


def resolve_slide_ini_path(slide_path: Path):
    # For MIRAX entry files (case_id.mrxs), datafile index may live in:
    # 1) side-by-side folder: <root>/<case_id>/Slidedat.ini
    # 2) same folder:         <folder>/Slidedat.ini
    if slide_path.suffix.lower() == ".mrxs":
        side_by_side = slide_path.parent / slide_path.stem / "Slidedat.ini"
        if side_by_side.exists():
            return side_by_side
        return slide_path.parent / "Slidedat.ini"
    return slide_path


def main():
    args = parse_args()
    args.output_csv.parent.mkdir(parents=True, exist_ok=True)

    rows_out = []
    with args.manifest_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            slide_id = row["slide_id"]
            slide_path = Path(row["slide_path"])
            slide_ini_path = resolve_slide_ini_path(slide_path)
            slide_dir = slide_ini_path.parent

            slide_ini_exists = slide_ini_path.exists()
            index_exists = (slide_dir / "Index.dat").exists()
            missing_files = []
            expected_count = 0

            if slide_ini_exists:
                expected = expected_datafiles(slide_ini_path)
                expected_count = len(expected)
                for filename in expected:
                    if not (slide_dir / filename).exists():
                        missing_files.append(filename)
            else:
                missing_files.append("Slidedat.ini")

            status = "ok"
            if (not slide_ini_exists) or (not index_exists) or missing_files:
                status = "incomplete"

            rows_out.append(
                {
                    "slide_id": slide_id,
                    "slide_path": str(slide_path),
                    "slide_ini_exists": int(slide_ini_exists),
                    "index_dat_exists": int(index_exists),
                    "expected_datafile_count": expected_count,
                    "missing_datafile_count": len(missing_files),
                    "status": status,
                    "missing_files": "|".join(missing_files),
                }
            )

    with args.output_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "slide_id",
                "slide_path",
                "slide_ini_exists",
                "index_dat_exists",
                "expected_datafile_count",
                "missing_datafile_count",
                "status",
                "missing_files",
            ],
        )
        writer.writeheader()
        writer.writerows(rows_out)

    total = len(rows_out)
    incomplete = sum(1 for r in rows_out if r["status"] != "ok")
    print(f"Validated {total} slides. Incomplete: {incomplete}. Report: {args.output_csv}")


if __name__ == "__main__":
    main()
